export const ERROR_CODES = {
  // Client & Request Validation Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',

  // Authentication & User Credential Errors
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_VERIFICATION_CODE: 'INVALID_VERIFICATION_CODE',
  INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  MISSING_REFRESH_TOKEN: 'MISSING_REFRESH_TOKEN',
  INVALID_SESSION: 'INVALID_SESSION',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',

  // Rate Limiting, Conflict & Server Errors
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
