export const ONE_SECOND_IN_MS = 1000;
export const ONE_MINUTE_IN_SECONDS = 60;
export const ONE_MINUTE_IN_MS = ONE_MINUTE_IN_SECONDS * ONE_SECOND_IN_MS;
export const ONE_HOUR_IN_SECONDS = 60 * ONE_MINUTE_IN_SECONDS;
export const ONE_HOUR_IN_MS = ONE_HOUR_IN_SECONDS * ONE_SECOND_IN_MS;
export const ONE_DAY_IN_HOURS = 24;
export const ONE_DAY_IN_SECONDS = ONE_DAY_IN_HOURS * ONE_HOUR_IN_SECONDS;
export const ONE_DAY_IN_MS = ONE_DAY_IN_HOURS * ONE_HOUR_IN_MS;

export const DEFAULT_ACCESS_TOKEN_EXPIRES_IN_SECONDS = 15 * ONE_MINUTE_IN_SECONDS; // 900 seconds (15 minutes)
export const DEFAULT_REFRESH_TOKEN_EXPIRES_IN_DAYS = 7;
export const DEFAULT_REFRESH_TOKEN_EXPIRES_IN_MS =
  DEFAULT_REFRESH_TOKEN_EXPIRES_IN_DAYS * ONE_DAY_IN_MS;

export const OTP_TTL_MS = 15 * ONE_MINUTE_IN_MS; // 15 minutes

export const AUTH_THROTTLE_LIMIT = 10;
export const AUTH_THROTTLE_TTL_MS = ONE_MINUTE_IN_MS; // 60,000 ms (1 minute)
